//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntProg2Odev2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimGrafigi
    {
        public int Id { get; set; }
        public string SehirAdi { get; set; }
        public Nullable<int> UretimMiktari2017 { get; set; }
        public Nullable<int> UretimMiktari2018 { get; set; }
        public Nullable<int> UretimMiktari2019 { get; set; }
        public Nullable<int> UretimMiktari2020 { get; set; }
        public Nullable<int> UretimMiktari2021 { get; set; }
        public Nullable<int> UretimMiktari2022 { get; set; }
    }
}
